
 <div class="logo-container">
                <div class="container">
                    
                    <div class="logo-wrapper clearfix">
                        <div class="logo">
                            <a href="http://www.stonybrook.edu/"><img src="/sites/all/libraries/unity/assets/images/stony-brook-university-logo.jpg" alt="Stony Brook University" width="357" height="68"></a>
                        </div>
                       <h1 class="site-name"><a href="/"><?php print $site_name ?></a></h1>
                    </div>
                    
                </div>
            </div>